### PR TITLE
Reimplement 'vagrant ssh' using guest-tools

### PR DESCRIPTION
**Pull request by bineesh-n**
Adding support for 'vagrant ssh' for pvm and macvm.

Requirements : public key should be present in the guest, if using - key authentication. Also, host should be providing the private key with box / with default identity.

Currently 'vagrant up' will fail to configure some shared directories - using ssh (After launching the VM). But 'vagrant ssh' will work perfectly.

### CODE REVIEW

**Comment by bineesh-n** [comment]
@legal90 SSH was not working in MacOS vms in M-Series chips, is the main problem. I changed the mechanism of getting the ip from "DHCP leases" to "Guest Tools", which will be more accurate. So I changed the IP detection mechanism for both type of VMs.

**Review by legal90 — CHANGES_REQUESTED** [review]
Current implementation with relying on the DHCP and "Shared" network has been done that way intentionally. The VMs not always have guest tools installed, or they could be out of date. Also, I'm not sure, in which version of Parallels Desktop the property `ip_configured` became available and what are the requirements for it to be set (compatibility with guest tools).

Using the DHCP lease for detecting the VM IP on the early stage is a way more reliable way than using the host <-> guest integration via `prlctl`.
Unfortunately, switching from the DHCP lease to `prlctl` output can brake the plugin for a various use-cases. That's why I don't think it's a right track for fixing this issue.

I would rather suggest to fix the SSH via Shared network & DHCP for all use cases, including yours on M-Series chips. 
I'm ready to help with that, but I don't have a possibility to test it on M-Series hardware.

Could you please file a new issue here with the details, describing the failure with the latest official provider version (v2.2.6)? Please also include this info:
1) Does `/Library/Preferences/Parallels/parallels_dhcp_leases` exist on your mac? 
2) Which IP vagrant tries to use? (It should be shown in `vagrant up` or `vagrant ssh-config` output)
3) Which IP do you see in the output `prlctl list -f <uuid> --json` ?

**Comment by bineesh-n** [comment]
@legal90 I've created the issue [here](https://github.com/Parallels/vagrant-parallels/issues/435). As you asked, prlctl does not require guest tools since PD16 actually (only for macvms guest tools required). Also, "ip_configured" is available since PD9 at least.

**Comment by legal90** [comment]
Thank you, @bineesh-n! Now I have a better understanding of the issue.

Let's see if we will find any other ways to determine the IP of `.macvms`.  If there will be no other options, I think we can still use both solutions at the same time, e.q.:

1) Try `read_guest_ip()`, as it is now.
2) If it returned an empty string (no IP in the lease) - try the method with `prlctl list -f <uuid> --json`

The wrapper function `ssh_ip()` is getting called in a loop, so vagrant with retry it again until it gets the IP from any of these 2 sources. In this case we wont break the compatibility for existing cases relying on DHCP lease.

**Comment by legal90** [comment]
@bineesh-n Thank you! I'll check it later today 👍

**Comment by legal90** [comment]
@bineesh-n I will run acceptance tests and release a new version of `vagrant-parallels` today.

**Comment by bineesh-n** [comment]
@legal90 No, it's not working.
`read_guest_ip_dhcp || read_guest_ip_prlctl` is returning "" for macvm. read_guest_ip_prlctl is never executed (read_guest_ip_dhcp is not nil anytime ? ).

**Comment by legal90** [comment]
@bineesh-n Oh, sorry about that! My bad - I didn't test it properly. 
Here is the fix: https://github.com/Parallels/vagrant-parallels/pull/440  Could you please review it?

**Pull request merged**
