### PR TITLE
Add driver for Parallels Desktop 12, drop EOL versions and deprecated options

### PR DESCRIPTION
**Pull request by legal90**
* Added driver for Parallels Desktop 12
* **Breaking**: Removed support for Parallels Desktop 8 and 9, since these versions have reached their EOL.
* **Breaking**: Removed deprecated customization options `use_linked_clone`, `regen_box_uuid`, `optimize_power_consumption`. Earlier these option have been marked as deprecated, so users were notified about that.

### CODE REVIEW

**Comment by legal90** [comment]
Due to breaking changes, I'm gonna release it in the scope of `v1.7.0`

**Comment by Gray-Wind** [comment]
It is good to transfer some methods from PD10 to Base, I think.

**Comment by legal90** [comment]
@Gray-Wind well, yes, that makes sense. 👍

**Comment by Gray-Wind** [comment]
LGTM 👍

**Pull request merged**
